### ISSUE TITLE
keyboard accessible markers

### ISSUE THREAD

**Issue by joehobson** [dylanb/a11yfy#9]
I'm working on a government site that uses an embedded Google map with custom markers. Our 508 compliance testing revealed some issues with keyboard navigation and the map (obviously). I really appreciate your work here. It goes a long way towards making the map accessible, but unfortunately it doesn't make the markers keyboard navigable. From what I've read, v3 of the maps API adds the markers as canvas elements so [a possible work around](http://blog.mojotech.com/selecting-google-maps-v3-markers-with-selenium-or-jquery/) is to set optimized to false for each marker and then use they you can use jquery to find them in the DOM.

Have you had any luck with markers or know of any other way to make them accessible?

**Comment by dylanb** [comment]
@joehobson apologies for the late reply. I have not had experience with trying to make the markers accessible.
